/**
 * SINGLE SOURCE OF TRUTH for all user-facing legal / disclaimer copy.
 *
 * Reviewed and approved by counsel (war-room #2, 2026-06-13). The `reviewPending`
 * flags below are retained as a structural signal and are all `false`; flip one
 * back to `true` (and re-engage counsel) if you materially change that section.
 *
 * Editing later: change strings here; bump DISCLAIMER_VERSION to re-prompt the
 * one-time first-session safety gate for everyone.
 */

// Bump on any material change to disclaimer/waiver/screening copy.
export const DISCLAIMER_VERSION = "2026-05-30";

export interface LegalSection {
  id: string;
  title: string;
  paragraphs: string[];
  reviewPending: boolean;
}

export const medicalDisclaimer: LegalSection = {
  id: "medical-disclaimer",
  title: "Medical Disclaimer",
  reviewPending: false,
  paragraphs: [
    "Carriage (AI Form Coach) provides general fitness information and movement feedback only. It is not medical advice, diagnosis, treatment, physical therapy, or a substitute for professional medical care. Using the app does not create a doctor-patient, therapist-patient, or trainer-client relationship.",
    "The app's real-time form feedback is generated by an automated, camera-based motion model that has technical limits and may be inaccurate, incomplete, or wrong for your body, environment, or movement. Do not rely on it as a substitute for a qualified trainer or licensed physical therapist, and do not use it to diagnose or treat any condition.",
    "Consult a physician before starting any exercise program, especially if you have a heart condition, high blood pressure, are pregnant, are recovering from injury or surgery, or have any condition that could be affected by exercise. Stop immediately and seek medical attention if you feel pain, dizziness, shortness of breath, chest pain, or any concerning symptom.",
  ],
};

export const assumptionOfRisk: LegalSection = {
  id: "assumption-of-risk",
  title: "Assumption of Risk & Release",
  reviewPending: false,
  paragraphs: [
    "Exercise carries inherent risks, including muscle strain, joint injury, falls, cardiac events, and in rare cases serious or life-threatening injury. By using the app you acknowledge these risks and voluntarily assume full responsibility for them.",
    "You are responsible for exercising within your ability, warming up, using appropriate space and equipment, and choosing movements suited to your condition. To the fullest extent permitted by law, you release and agree not to hold Carriage (AI Form Coach), its creator, and its affiliates liable for any injury, loss, or damage arising from your use of the app.",
    "You confirm you are at least 18 years old and legally able to accept this release. If any part of this release is unenforceable in your jurisdiction, the remainder continues to apply to the maximum extent permitted by law.",
  ],
};

export interface SafetyScreening {
  intro: string;
  criteria: string[];
  attestationLabel: string;
  reviewPending: boolean;
}

// Show-don't-store: criteria are DISPLAYED for self-evaluation; the user's
// answers are NEVER collected or stored — only the single attestation below.
export const safetyScreening: SafetyScreening = {
  reviewPending: false,
  intro:
    "Before you start, please check yourself against the list below. If any apply, talk to a doctor before using the coach.",
  criteria: [
    "A heart condition, or chest pain during physical activity",
    "Dizziness, fainting, or loss of balance",
    "Pregnancy, or recent childbirth",
    "Recent surgery, injury, or a joint/bone problem made worse by exercise",
    "A condition a doctor has told you limits your physical activity",
  ],
  attestationLabel:
    "I am 18 or older, I am healthy enough to exercise, none of the above prevents me from exercising safely, and I will consult a physician if I am unsure.",
};

export const inSessionMicroDisclaimer =
  "Not medical advice · stop if you feel pain or dizziness";

export const signupConsentLabel =
  "I am 18 or older and I have read and agree to the Terms, Privacy Policy, and Medical Disclaimer & Assumption of Risk.";

// Sections added to /terms (strengthened safety + liability), rendered from here.
export const termsSafety: LegalSection = {
  id: "safety",
  title: "Safety and health disclaimer",
  reviewPending: false,
  paragraphs: [
    "The app provides general fitness guidance only and is not medical advice, physical therapy, diagnosis, treatment, or emergency support. Its automated form feedback may be inaccurate; it is not a substitute for a qualified trainer or licensed physical therapist.",
    "Stop exercising if you feel pain, dizziness, or discomfort. You are responsible for exercising safely, warming up, and choosing movements that fit your condition. See the full Medical Disclaimer & Assumption of Risk.",
  ],
};

export const termsLiability: LegalSection = {
  id: "liability",
  title: "Warranty and liability limits",
  reviewPending: false,
  paragraphs: [
    "The app is provided on an as-is and as-available basis. To the maximum extent permitted by law, we disclaim all warranties and are not liable for any injury or for indirect, incidental, or consequential damages arising from use of the service.",
    "You use the app voluntarily and assume the risks of exercise. Where law does not allow some of these limitations, they apply to the maximum extent permitted. Governing law: the laws of the State of Florida, United States, without regard to its conflict-of-laws rules.",
  ],
};

export const termsEligibility: LegalSection = {
  id: "eligibility",
  title: "Eligibility (18+)",
  reviewPending: false,
  paragraphs: [
    "The beta is available only to adults 18 years or older. By creating an account you confirm you are at least 18.",
  ],
};

export const privacyHealthData: LegalSection = {
  id: "camera-and-health",
  title: "Camera, motion, and health data",
  reviewPending: false,
  paragraphs: [
    "Live pose detection runs on your device in your browser. Your camera video is processed locally and is not transmitted to or stored on our servers.",
    "The pre-exercise safety check is a self-attestation only: we do not collect or store your answers to the health screening questions. We record only that you accepted the current disclaimer version and when.",
    "For users in the EU/UK and similar regions, you have data-subject rights (access, deletion, etc.). The service is for adults 18+. Contact us to exercise your rights.",
  ],
};
